-- Generated by shipdaily for TheEntryLevelDevJobsAreD
-- Run this in the Supabase SQL editor, or via supabase db push.

create table if not exists public.items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  title text,
  body text,
  created_at timestamptz default now()
);

alter table public.items enable row level security;

create policy "Users manage own rows" on public.items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
