/**
 * Scaffold a Next.js 14 + Supabase + Tailwind app from a spec.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

function pgType(t) {
  const map = {
    uuid: 'uuid',
    text: 'text',
    int: 'integer',
    integer: 'integer',
    bigint: 'bigint',
    bool: 'boolean',
    boolean: 'boolean',
    timestamptz: 'timestamptz',
    jsonb: 'jsonb',
    numeric: 'numeric',
  };
  return map[t.toLowerCase()] ?? t;
}

function generateSchemaSQL(spec) {
  const out = [];
  out.push('-- Generated by shipdaily for ' + spec.name);
  out.push('-- Run this in the Supabase SQL editor, or via supabase db push.');
  out.push('');
  for (const t of spec.tables) {
    const cols = t.columns.map(c => {
      const parts = [`  ${c.name} ${pgType(c.type)}`];
      if (c.primary) parts.push('primary key default gen_random_uuid()');
      if (c.references) parts.push(`references ${c.references}(id) on delete cascade`);
      if (c.default) parts.push(`default ${c.default}`);
      if (c.notNull) parts.push('not null');
      return parts.join(' ');
    }).join(',\n');
    out.push(`create table if not exists public.${t.name} (`);
    out.push(cols);
    out.push(');');
    out.push('');
    out.push(`alter table public.${t.name} enable row level security;`);
    out.push('');
    out.push(`create policy "Users manage own rows" on public.${t.name}`);
    out.push(`  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);`);
    out.push('');
  }
  return out.join('\n');
}

function packageJson(spec) {
  return JSON.stringify({
    name: spec.slug,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      next: '^14.2.0',
      react: '^18.3.0',
      'react-dom': '^18.3.0',
      '@supabase/supabase-js': '^2.45.0',
      '@supabase/ssr': '^0.5.0',
    },
    devDependencies: {
      '@types/node': '^20',
      '@types/react': '^18',
      typescript: '^5',
      tailwindcss: '^3.4.0',
      autoprefixer: '^10.4.0',
      postcss: '^8.4.0',
      eslint: '^8',
      'eslint-config-next': '^14.2.0',
    },
  }, null, 2);
}

function nextConfig() {
  return `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
module.exports = nextConfig;
`;
}

function tsconfig() {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2);
}

function tailwindConfig() {
  return `module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: { extend: {} },
  plugins: [],
};
`;
}

function globalsCss() {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: dark;
}

html, body {
  background: #0a0a08;
  color: #ede9e3;
  font-family: -apple-system, 'Segoe UI', Helvetica, Arial, sans-serif;
}
`;
}

function postcssConfig() {
  return `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };
`;
}

function envExample() {
  return `# Supabase credentials (Project Settings → API in Supabase dashboard)
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-server-only
`;
}

function supabaseClient() {
  return `import { createBrowserClient } from '@supabase/ssr';

export function getBrowserClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}
`;
}

function supabaseServer() {
  return `import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';

export function getServerClient() {
  const cookieStore = cookies();
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) { return cookieStore.get(name)?.value; },
        set(name: string, value: string, options: any) {
          try { cookieStore.set({ name, value, ...options }); } catch {}
        },
        remove(name: string, options: any) {
          try { cookieStore.set({ name, value: '', ...options }); } catch {}
        },
      },
    }
  );
}
`;
}

function rootLayout(spec) {
  return `import './globals.css';

export const metadata = {
  title: '${spec.name}',
  description: '${spec.tagline}',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function landingPage(spec) {
  return `import Link from 'next/link';

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center px-6">
      <div className="max-w-2xl text-center">
        <h1 className="text-5xl md:text-7xl font-light tracking-tight mb-6">${spec.name}</h1>
        <p className="text-xl text-zinc-400 mb-10 leading-relaxed">${spec.tagline}</p>
        <Link
          href="/app"
          className="inline-block px-6 py-3 bg-emerald-700 hover:bg-emerald-600 text-white rounded-md font-medium transition"
        >
          Start free →
        </Link>
        <p className="mt-12 text-sm text-zinc-500">${spec.target_user}</p>
      </div>
    </main>
  );
}
`;
}

function appPage(spec) {
  const firstTable = spec.tables[0]?.name ?? 'items';
  return `'use client';

import { useState, useEffect } from 'react';
import { getBrowserClient } from '@/lib/supabase-browser';

export default function AppPage() {
  const [items, setItems] = useState<any[]>([]);
  const [title, setTitle] = useState('');
  const [loading, setLoading] = useState(true);
  const supabase = getBrowserClient();

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    const { data } = await supabase.from('${firstTable}').select('*').order('created_at', { ascending: false }).limit(50);
    setItems(data ?? []);
    setLoading(false);
  }

  async function add() {
    if (!title.trim()) return;
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) { window.location.href = '/?signin=1'; return; }
    await supabase.from('${firstTable}').insert({ user_id: user.id, title });
    setTitle('');
    load();
  }

  return (
    <main className="min-h-screen px-6 py-12 max-w-3xl mx-auto">
      <h1 className="text-3xl font-light mb-8">${spec.name}</h1>
      <div className="flex gap-2 mb-8">
        <input
          value={title}
          onChange={e => setTitle(e.target.value)}
          placeholder="Add something..."
          className="flex-1 bg-zinc-900 border border-zinc-800 rounded px-4 py-2 focus:border-emerald-600 outline-none"
          onKeyDown={e => e.key === 'Enter' && add()}
        />
        <button
          onClick={add}
          className="bg-emerald-700 hover:bg-emerald-600 px-4 py-2 rounded text-white font-medium"
        >
          Add
        </button>
      </div>
      {loading ? (
        <p className="text-zinc-500">Loading...</p>
      ) : items.length === 0 ? (
        <p className="text-zinc-500">No items yet. Add one above.</p>
      ) : (
        <ul className="space-y-2">
          {items.map(item => (
            <li key={item.id} className="bg-zinc-900 border border-zinc-800 rounded px-4 py-3">
              {item.title}
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}
`;
}

function readme(spec) {
  return `# ${spec.name}

> ${spec.tagline}

${spec.pitch}

## Getting started

\`\`\`bash
npm install
cp .env.example .env.local
# Fill in Supabase credentials in .env.local
npm run dev
\`\`\`

## Database

Run \`schema.sql\` in the Supabase SQL editor, or via \`supabase db push\` if using local Supabase.

## Deploy

\`\`\`bash
vercel deploy --prod
\`\`\`

Then add \`NEXT_PUBLIC_SUPABASE_URL\` and \`NEXT_PUBLIC_SUPABASE_ANON_KEY\` to Vercel env.

## Stack

- Next.js 14 (App Router)
- Supabase (Postgres + Auth + RLS)
- Tailwind CSS
- TypeScript

## Spec

See [SPEC.md](./SPEC.md) for the full product spec that generated this scaffold.

---

Generated by [shipdaily](https://github.com/snedco/shipdaily) on ${new Date().toISOString().slice(0, 10)}.
`;
}

function gitignore() {
  return `node_modules
.next
out
.env.local
.env
.vercel
*.log
.DS_Store
`;
}

export async function scaffoldApp(appDir, spec) {
  // Top-level files
  await writeFile(join(appDir, 'package.json'), packageJson(spec), 'utf-8');
  await writeFile(join(appDir, 'next.config.js'), nextConfig(), 'utf-8');
  await writeFile(join(appDir, 'tsconfig.json'), tsconfig(), 'utf-8');
  await writeFile(join(appDir, 'tailwind.config.js'), tailwindConfig(), 'utf-8');
  await writeFile(join(appDir, 'postcss.config.js'), postcssConfig(), 'utf-8');
  await writeFile(join(appDir, '.env.example'), envExample(), 'utf-8');
  await writeFile(join(appDir, '.gitignore'), gitignore(), 'utf-8');
  await writeFile(join(appDir, 'README.md'), readme(spec), 'utf-8');
  await writeFile(join(appDir, 'schema.sql'), generateSchemaSQL(spec), 'utf-8');

  // app/ dir
  await mkdir(join(appDir, 'app'), { recursive: true });
  await writeFile(join(appDir, 'app', 'globals.css'), globalsCss(), 'utf-8');
  await writeFile(join(appDir, 'app', 'layout.tsx'), rootLayout(spec), 'utf-8');
  await writeFile(join(appDir, 'app', 'page.tsx'), landingPage(spec), 'utf-8');

  // app/app/page.tsx (main feature)
  await mkdir(join(appDir, 'app', 'app'), { recursive: true });
  await writeFile(join(appDir, 'app', 'app', 'page.tsx'), appPage(spec), 'utf-8');

  // lib/
  await mkdir(join(appDir, 'lib'), { recursive: true });
  await writeFile(join(appDir, 'lib', 'supabase-browser.ts'), supabaseClient(), 'utf-8');
  await writeFile(join(appDir, 'lib', 'supabase-server.ts'), supabaseServer(), 'utf-8');

  return appDir;
}
